networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    environment:
      # Add both HTTP/HTTPS + optional www for production access
      - ALLOWED_ORIGINS=http://localhost,http://localhost:3000,https://mentorium.tech,http://mentorium.tech,https://www.mentorium.tech,http://www.mentorium.tech
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    networks:
      - dev
